package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.32

import (
	"context"
	"server/graphql/generated/model"
)

// Animes is the resolver for the animes field.
func (r *queryResolver) Animes(ctx context.Context) ([]*model.Anime, error) {
	res, err := r.anime.AnimeList(ctx)
	if err != nil {
		return nil, err
	}

	animes := make([]*model.Anime, len(res))
	for i, v := range res {
		animes[i] = &model.Anime{
			AnimeID: v.AnimeID,
			Name:    v.Name,
		}
	}
	return animes, nil
}

// Anime is the resolver for the anime field.
func (r *queryResolver) Anime(ctx context.Context, animeID int) (*model.Anime, error) {
	res, err := r.anime.GetAnimeByID(ctx, animeID)
	if err != nil {
		return nil, err
	}

	anime := &model.Anime{
		AnimeID: res.AnimeID,
		Name:    res.Name,
	}

	return anime, nil
}
