package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.32

import (
	"context"
	"fmt"
	"server/graphql/generated/model"
)

// Countries is the resolver for the countries field.
func (r *queryResolver) Countries(ctx context.Context) ([]*model.Country, error) {
	panic(fmt.Errorf("not implemented: Countries - countries"))
}

// Country is the resolver for the country field.
func (r *queryResolver) Country(ctx context.Context, countryID int) (*model.Country, error) {
	panic(fmt.Errorf("not implemented: Country - country"))
}
