package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.32

import (
	"context"
	"fmt"
	"server/graphql/generated/model"
)

// Genders is the resolver for the genders field.
func (r *queryResolver) Genders(ctx context.Context) (*model.Gender, error) {
	panic(fmt.Errorf("not implemented: Genders - genders"))
}

// Gender is the resolver for the gender field.
func (r *queryResolver) Gender(ctx context.Context, genderID int) (*model.Gender, error) {
	panic(fmt.Errorf("not implemented: Gender - gender"))
}
