package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.32

import (
	"context"
	"fmt"
	"server/graphql/generated/model"
)

// Guides is the resolver for the guides field.
func (r *queryResolver) Guides(ctx context.Context) ([]*model.Guide, error) {
	panic(fmt.Errorf("not implemented: Guides - guides"))
}

// Guide is the resolver for the guide field.
func (r *queryResolver) Guide(ctx context.Context, guideID int) (*model.Guide, error) {
	panic(fmt.Errorf("not implemented: Guide - guide"))
}
